In [11]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,6,7])
print(arr1)
print(type(arr1))
arr2=np.array([[2,4,2],[4,2,5]])  #2 rows 3 columns 


[1 2 3 4 5 6 6 7]
<class 'numpy.ndarray'>


In [12]:
arr2.shape


(2, 3)

In [13]:
arr2.dtype



dtype('int32')

In [8]:
#for blank array
np.zeros(5)
np.zeros((6,3))   # 6 rows by 3 columns 


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(5).dtype


dtype('float64')

In [23]:
np.empty((3,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
arr1*arr1


array([ 1,  4,  9, 16, 25, 36, 36, 49])

In [21]:
#arr1**arr1


In [24]:
1/arr1


array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.16666667, 0.14285714])

# Silicing in numpy


In [25]:
arr1


array([1, 2, 3, 4, 5, 6, 6, 7])

In [36]:
arr3=np.array([3,4,56,6,6,100])


In [38]:
arr3[2:6]


array([ 56,   6,   6, 100])

In [39]:
arr3[0]=15


In [43]:
arr3


array([ 15,   4,  56,   6,   6, 100])

In [44]:
arr4=arr3.copy()


In [45]:
arr4


array([ 15,   4,  56,   6,   6, 100])

In [49]:
arr4[2]=200  #put 200 in index 2  56 replace to 200



In [47]:
arr4


array([ 15,   4, 200,   6,   6, 100])