In [5]:
import numpy as np

In [6]:
arr1=np.array([[1,3,4],[5,6,7]])

In [9]:
arr1.sum(axis=0)

#axis =1 for row
#and axis=0 for column  1+4=6   3+5=9  4+7=11

#two access define one 0 axis 1

array([ 6,  9, 11])

In [14]:
arr2=np.array([[2,3,5],[4,6,8]])

In [15]:
arr1.dot(arr2.transpose())

array([[ 31,  54],
       [ 63, 112]])

In [23]:
arr1.transpose()

array([[1, 5],
       [3, 6],
       [4, 7]])

In [19]:
len(dir(np))
#dir(np)       #gives directories of np

599

In [21]:
np.cross(arr1,arr2)

array([[  3,   3,  -3],
       [  6, -12,   6]])

In [26]:
arr3=np.array([[3,2,1],[6,4,2]])

In [27]:
np.sort(arr3)

array([[1, 2, 3],
       [2, 4, 6]])

In [31]:
%%time
np.sort(arr3,axis=0 ,kind='mergesort')

CPU times: total: 0 ns
Wall time: 999 µs


array([[3, 2, 1],
       [6, 4, 2]])