In [1]:
import numpy as np


In [2]:
n=np.arange(7)


In [3]:
n


array([0, 1, 2, 3, 4, 5, 6])

In [9]:
n2=np.array([3,4,5,6,7,8,9,10,11,12,13,14])
n2=n2.reshape(6,2)
#reshape the array 6 rows and 2 columns


In [8]:
n2


array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [10]:
np.argsort(n2)


array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int64)

In [11]:
np.argmin(n2)  #3 is smallest value in 0 index


0

In [13]:
np.argmax(n2)   #14 is largest value in 11 index


11

In [18]:
#np.argsort(n2 ,axis=0)
